2025-01-16 09:23:46,861 | WARNING | Not Found: /delete/3/
2025-01-16 09:23:46,863 | WARNING | "GET /delete/3/ HTTP/1.1" 404 3732
2025-01-16 09:24:04,984 | INFO | Added Feedback | File: No file | Email: kr.karov@gmail.com
2025-01-16 09:24:24,413 | INFO | Deleted Feedback | Email: kr.karov@gmail.com | Message: teeeeeeest | File: No file
2025-01-16 09:24:45,215 | WARNING | Not Found: /delete/5/
2025-01-16 09:24:45,215 | WARNING | "GET /delete/5/ HTTP/1.1" 404 3732
2025-01-16 09:27:52,746 | INFO | Added Feedback | File: ANS-C01 Study Guide.txt | Email: kr.karov@hotmail.com
2025-01-16 09:34:00,906 | INFO | Added Feedback | File: No file | Email: kr.karov+komsed@gmail.com
2025-01-16 09:34:11,242 | ERROR | Internal Server Error: /update/7/
Traceback (most recent call last):
  File "/Users/karov/.local/share/virtualenvs/feedback_logger-bf575s9K/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/karov/.local/share/virtualenvs/feedback_logger-bf575s9K/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/karov/dev/DevOps-Projects/Django/feedback_logger/feedback/views.py", line 48, in update_feedback
    old_message = feedback.message
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'feedback' where it is not associated with a value
2025-01-16 09:34:11,243 | ERROR | "GET /update/7/ HTTP/1.1" 500 69283
2025-01-16 09:34:18,251 | ERROR | Internal Server Error: /update/6/
Traceback (most recent call last):
  File "/Users/karov/.local/share/virtualenvs/feedback_logger-bf575s9K/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/karov/.local/share/virtualenvs/feedback_logger-bf575s9K/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/karov/dev/DevOps-Projects/Django/feedback_logger/feedback/views.py", line 48, in update_feedback
    old_message = feedback.message
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'feedback' where it is not associated with a value
2025-01-16 09:34:18,252 | ERROR | "GET /update/6/ HTTP/1.1" 500 69283
